name: Build and deploy .NET 8 Blazor WebAssembly to Static Web App OceanVMSCliennt
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, closed ]

env:
  API_DIRECTORY: ''
  DEPLOYMENT_ENVIRONMENT: preview

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: .
        run: dotnet restore

      - name: Publish (Release)
        working-directory: .
        run: dotnet publish -c Release -o publish

      - name: Build And Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.OceanVMSCliennt_SPN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          deployment_environment: ${{ env.DEPLOYMENT_ENVIRONMENT }}
          app_location: "/" 
          api_location: ${{ env.API_DIRECTORY }}
          app_artifact_location: "publish/wwwroot"
